static void getclientflags(Client *c);
static void getclientfields(Client *c);
static void getworkspacestate(Workspace *ws);
static void persistworkspacestate(Workspace *ws);
static void setcurrentdesktop(void);
static void setdesktopnames(void);
static void setfloatinghint(Client *c);
static void setclientflags(Client *c);
static void setclientfields(Client *c);
static void setnumdesktops(void);
static void setviewport(void);
static void updatecurrentdesktop(void);