static void getclientflags(Client *c);
static void getclienttags(Client *c);
static void persistmonitorstate(Monitor *m);
static void setcurrentdesktop(void);
static void setdesktopnames(void);
static void setfloatinghint(Client *c);
static void setclientflags(Client *c);
static void setclienttags(Client *c);
static void setnumdesktops(void);
static void setviewport(void);
static void updatecurrentdesktop(void);