static void getclientflags(Client *c);
static void getclientfields(Client *c);
static void getworkspacestate(Workspace *ws);
static void persistworkspacestate(Workspace *ws);
static void savewindowfloatposition(Client *c, Monitor *m);
static int restorewindowfloatposition(Client *c, Monitor *m);
static void setdesktopnames(void);
static void setfloatinghint(Client *c);
static void setclientflags(Client *c);
static void setclientfields(Client *c);
static void setnumdesktops(void);
static void setviewport(void);
static void updatecurrentdesktop(void);
static void updateclientdesktop(Client *c);
