static Client **clientptr(Client *c);
static void getclientindices(Client *c, int *nth_client, int *nth_tiled, int *nth_floating, int *nth_master, int *nth_stack, int *num_clients, int *num_tiled, int *num_floating, int *num_master, int *num_stack);
static int ismasterclient(Client *c);
static Client *lastclient(Client *c);
static Client *lasttiled(Client *c);
static Client *nexttiled(Client *c);
static Client *nexthidden(Client *c);
static Client *snexthidden(Client *c);
static Client *nthmaster(Client *c, int n, int reduce);
static Client *nthstack(Client *c, int n, int reduce);
static Client *nthtiled(Client *c, int n, int reduce);
static Client *inctiled(Client *sel, int n);
static Client *prevtiled(Client *c);
static Client *prevsel(void);
static void swap(Client *a, Client *b);
