// static void copysizehints(Client *from, Client *to);
static pid_t getparentprocess(pid_t p);
static int isdescprocess(pid_t p, pid_t c);
static int replaceclient(Client *old, Client *new);
static int swallowclient(Client *p, Client *c);
static Client *swallowingparent(Window w);
static Client *swallowingroot(Window w);
static Client *termforwin(const Client *c);
static void unswallow(const Arg *arg);
static pid_t winpid(Window w);
static void swallow(const Arg *arg);